# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: meow_facts_api
      conn_type: http
      conn_host: https://meowfacts.herokuapp.com/

    - conn_id: cluster
      conn_type: kubernetes
      conn_extra:
        kube_config_path: /usr/local/airflow/include/.kube
        namespace: general

